# Site settings
baseurl = "https://brawijayasensorycenter.id"
languageCode = "en-us"
title = "Sensory and Applied Food Science Research Group"
theme = "hugo-agency-theme"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[params]
  # You can use Markdown syntax for urls [text](//url.to/source) or
  # most longer texts.
  #
  # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # To provide some metadata for search engines feel free to add a few
  # information about you and your website.
  name = "Sensory and Applied Food Science Research Group"
  description = "Sensory and Applied Food Science Research Group"
  # email = "your@email.com"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Possibility to disable external/additional fonts
  # Exception: Fontawesome
  disableFonts = false

  # 404 error customization
  [params.error404]
    heading = "Maaf, laman yang Anda cari tidak dapat ditemukan."
    text = "Silakan kembali ke [halaman utama](/)"

  # Optional piwik tracking
  #[params.analytics.piwik]
  #  URL = "https://stats.example.com"
  #  ID = "42"
  #  # Track all subdomains with "*.example.com"
  #  domain = "www.example.com"
  #  # Optional integrity check hash
  #  hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="

  # Navigation
  [params.navigation]
    brand = "Brawijaya Sensory Center"
    # Optional logo as brand stored in img/
    #logo = "logo.svg"
    services = "Ruang Lingkup"
    portfolio = "Publikasi dan Kegiatan"
    about = "Tentang Kami"
    team = "Anggota"
    contact = "Kontak"

    # Add custom links. Those can be pre- and postpended to the default menu above.
    # Use the weight attribute to order your custom links. Uncomment the example
    # below and replace the values with your own.

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10


  # Hero section
  [params.hero]
    # To change the background image of the hero, replace 'header-bg.jpg' in
    # the 'static/img' folder.
    title = "Kelompok Kajian Sensoris dan Pangan Terapan"
    subtitle = ""
    buttonText = "Ruang Lingkup"


  # Services section
  [params.services]
    enable = true
    title = "Ruang Lingkup"
    subtitle = "Ruang lingkup kegiatan dan penelitian Kelompok Kajian Sensoris dan Pangan Terapan Universitas Brawijaya"

    [[params.services.row]]

    [[params.services.row.list]]
      icon = "fa-thumbs-up"
      title = "Mutu Pangan"
      description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."
      url = "#"

    [[params.services.row.list]]
      icon = "fa-users"
      title = "Perilaku Konsumen"
      description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."
      url = "#"

    [[params.services.row.list]]
      icon = "fa-book"
      title = "Manajemen Keamanan Pangan dan Kehalalan"
      description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."
      url = "#"

    [[params.services.row.list]]
      icon = "fa-cart-plus"
      title = "Pemasaran"
      description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."
      url = "#"

    [[params.services.row.list]]
      icon = "fa-users"
      title = "Psikologi"
      description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."
      url = "#"

    [[params.services.row.list]]
      icon = "fa-comments"
      title = "Kulinologi Pangan Tradisional"
      description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."
      url = "#"

    [[params.services.row.list]]
      icon = "fa-coffee"
      title = "Gastronomi Molekuler"
      description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."
      url = "#"

    [[params.services.row.list]]
      icon = "fa-chain"
      title = "Sensori Syaraf"
      description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."
      url = "#"

  # Portfolio section
  [params.portfolio]
    enable = true
    # All projects defined in their own files. You can find example projects
    # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    title = "Publikasi dan Kegiatan"
    subtitle = "Lorem ipsum dolor sit amet consectetur."

    [params.portfolio.modal]
      client = "Bekerjasama dengan"
      date = "Tanggal"
      category = "Kategori"
      buttonText = "Tutup"


    # About section
  [params.about]
    enable = true
    title = "Tentang Kami"
    subtitle = "Lorem ipsum dolor sit amet consectetur."
    endpoint = "Brawijaya Sensory Center"

    # The events will be listed from the top to the bottom.
    # All images are stored under 'static/img/about'.
    # Replace them with your own.
    [[params.about.events]]
      img = "1.jpg"
      date = ""
      title = "Visi"
      description = "Menjadi pusat pengembangan ilmu dan teknologi di bidang sensoris dan pangan terapan yang terkemuka dalam rangka mendukung industri pangan dan hasil pertanian di pasar global"

    [[params.about.events]]
      img = "2.jpg"
      date = ""
      title = "Misi"
      description = "(1) Menghasilkan karya ilmiah di bidang sensoris dan ilmu pangan terapan yang memberikan kontribusi bagi industri dan masyarakat; (2) Meningkatkan kualitas hasil penelitian di bidang sensoris dan ilmu pangan terapan"

    [[params.about.events]]
      img = "3.jpg"
      date = ""
      title = "Tujuan"
      description = "(1) Meningkatkan rekam jejak melalui akselerasi publikasi bereputasi dalam rangka mengembangkan ilmu dan teknologi dalam bidang ilmu sensoris dan pangan terapan; (2) Membentuk jejaring kerjasama dalam rangka peningkatan mutu penelitian berbasis ilmu sensori dan pangan terapan serta inisiasi pembentukan asosiasi profesi berbasis ilmu sensori dan pangan terapan"


  # Team section
  [params.team]
    enable = true
    # Possibility to center items
    #center = true
    title = "Anggota"
    subtitle = "Kelompok Kajian Sensoris dan Pangan Terapan beranggotakan para ahli di bidang ilmu sensoris pangan dan pangan terapan"
    description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut eaque, laboriosam veritatis, quos non quis ad perspiciatis, totam corporis ea, alias ut unde."

    # All team member's pictures are stored under 'static/img/team'.
    # Replace them with your own too.
    # Suggestion: Image size should be at least 360px*360px or the alignment might be affected.
    [[params.team.members]]
      img = "1.jpg"
      name = "Kiki Fibrianto, STP, MPhil, PhD"
      position = "Ketua"
      scope = [
        "Sensori pangan, studi konsumen, gastronomi, dan kulinologi"
      ]
      # For bio markdown and even multiline strings are available.
      social = [
        ["fa-envelope", "mailto:kiki.fibrianto@ub.ac.id"],
        ["fa-globe", "http://thp.ub.ac.id/profildosen/dosen_detail.php?idx_dosen=41"]
      ]

    [[params.team.members]]
      img = "2.jpg"
      name = "Wenny Bekti Sunarharum, STP, MFoodSt, PhD"
      position = "Sekretaris"
      scope = [
        "Flavor Pangan, ilmu sensoris, gastronomi molekuler, kulinologi"
      ]
      # For bio markdown and even multiline strings are available.
      social = [
        ["fa-envelope", "mailto:wbsunarharum@ub.ac.id"],
        ["fa-globe", "http://thp.ub.ac.id/profildosen/dosen_detail.php?idx_dosen=39"]
      ]

    [[params.team.members]]
      img = "1.jpg"
      name = "Prof. Dr. Ir. Harijono, M.App.Sc"
      position = "Divisi Pengembangan Pangan Tradisional"
      scope = [
        "Teknologi hasil pertanian dan teknologi pengolahan pangan"
      ]
      # For bio markdown and even multiline strings are available.
      social = [
        ["fa-envelope", "mailto:harijono_07@yahoo.com"],
        ["fa-globe", "http://thp.ub.ac.id/profildosen/dosen_detail.php?idx_dosen=19"]
      ]

    [[params.team.members]]
      img = "1.jpg"
      name = "Dr. Ir. Sudarminto Setyo Yuwono, M.App.Sc"
      position = "Divisi Teknologi Pangan Terapan"
      scope = [
        "Keteknikan pangan"
      ]
      # For bio markdown and even multiline strings are available.
      social = [
        ["fa-envelope", "mailto:ssyuwono2004@yahoo.com"],
        ["fa-phone", "http://thp.ub.ac.id/profildosen/dosen_detail.php?idx_dosen=21"]
      ]

    [[params.team.members]]
      img = "2.jpg"
      name = "Erni Sofia Murtini, STP., MP., PhD"
      position = "Pengembangan Pangan Tradisional"
      scope = [
        "Ilmu kimiawi serealia"
      ]
      # For bio markdown and even multiline strings are available.
      social = [
        ["fa-envelope", "mailto:erni.murtini@ub.ac.id"],
        ["fa-globe", "http://thp.ub.ac.id/profildosen/dosen_detail.php?idx_dosen=23"]
      ]

    [[params.team.members]]
      img = "2.jpg"
      name = "Indria Purwantiningrum, STP, MSi"
      position = "Divisi Mutu dan Keamanan Pangan"
      scope = [
        "Menejemen mutu pangan dan pengembangan produk"
      ]
      # For bio markdown and even multiline strings are available.
      social = [
        ["fa-envelope", "mailto:airdni @yahoo.com"],
        ["fa-globe", "http://thp.ub.ac.id/profildosen/dosen_detail.php?idx_dosen=40"]
      ]

    [[params.team.members]]
      img = "2.jpg"
      name = "Elok Waziiroh, STP, MSi"
      position = "Bendahara"
      scope = [
        "Keteknikan pangan dan komponen senyawa bioaktif"
      ]
      # For bio markdown and even multiline strings are available.
      social = [
        ["fa-envelope", "mailto:elokwz@yahoo.co.id"],
        ["fa-globe", "http://thp.ub.ac.id/profildosen/dosen_detail.php?idx_dosen=27"]
      ]

  # Client section
    [params.clients_list]
      enable = true
      # Possibility to center items
      #center = true
      # Optional client title specifying the involvement
      title = "Jaringan kerjasama"

      # All the clients' logos are stored under 'static/img/logos'.
      # Replace them with your clients's logos.
      # Suggestion: .svg in the size of 280px*80px looks good
      [[params.clients]]
        logo = "sensolutionid.png"
        link = "https://sensolution.ID"


  # Contact section
  [params.contact]
    enable = true
    title = "Hubungi Kami"
    subtitle  = "Lorem ipsum dolor sit amet consectetur."
    buttonText = "Kirim Pesan"
    # netlify = true

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!

    # It is possible to substitute formspring with other providers
    # as an example the mailout plugin from caddy.
    # Provide the post URL for the form and depending on the provider
    # add some custom JS script to finish the implementation.
    # postURL = "https://example.com/mailout/"

    email = "your@email.com"

    # Success and error message overwrite for async contact form
    #thanks = "Thank you for awesomely contacting us."
    #error = "Message could not be send. Please contact us at mail@example.com instead."

    [params.contact.captcha]
      # sitekey = ""

    # 'warning' defines error messages for invalid inputs
    [params.contact.form.name]
      text = "Nama *"
      warning = "Mohon tuliskan nama."

    [params.contact.form.email]
      text = "Alamat surel *"
      warning = "Mohon tuliskan alamat surel."

    [params.contact.form.phone]
      text = "Nomor telepon *"
      warning = "Mohon tuliskan nomor telepon."

    [params.contact.form.message]
      text = "Pesan *"
      warning = "Silakan tuliskan pesan."

      # Add optional form fields to identify contact forms
      #[[params.contact.form.hidden]]
      #  name = "someID"
      #  value = "example.com"
      #
      #[[params.contact.form.hidden]]
      # Special values for name such as "page" and "site" will be autofilled
      #  name = "page"

  # Footer section
  [params.footer]
    enable = false
    copyright = "Published under the Apache License 2.0."

    [[params.footer.social]]
      icon = "fa-twitter"
      link = "#"
      title = "Twitter"

    [[params.footer.social]]
      icon = "fa-facebook"
      link = "#"
      title = "Facebook"

    [[params.footer.social]]
      icon = "fa-linkedin"
      link = "#"
      title = "LinkedIn"

    [[params.footer.quicklinks]]
      text = "Privacy Policy"
      link = "#"

    [[params.footer.quicklinks]]
      text = "Terms of Use"
      link = "#"
